### ISSUE TITLE
[IMPORTANTE] - Actualizaciones del repositorio

### ISSUE THREAD

**Issue by Britooo09** [Britooo09/asigLiceo#3]
# Sobre las actualizaciones
Actualizar el repositorio **cada mes** con las _asignaciones y trabajos_ realizados en ese período de tiempo.
Al hacer esto, se mantiene un ambiente de trabajo mucho más **organizado y limpio**.
`En este tema se llevará un recuento de los meses en que se actualizó el repositorio.`

# Actualizaciones importantes
:heavy_check_mark: Subida inicial.
:heavy_check_mark: Actualización de octubre.
:exclamation: Actualización de noviembre.__*__
:exclamation: Actualización de diciembre.
:heavy_check_mark: Actualización de enero.
:exclamation: Actualización de febrero.
:exclamation: Actualización de marzo.
:heavy_check_mark: Actualización de abril.

`[*] = en noviembre se hizo una subida a una rama secundaria --nov-update, pero el pull request no fue aceptado a tiempo.`

**Comment by agBAZE** [comment]
Se actualiza la lista, añadiendo el mes de enero.
